import java.util.Scanner;
public class PinoutTracker {
    private String d1 = "";
    private String d2 = "";
    private String d3 = "";
    private String d4 = "";
    private String d5 = "";
    private String d6 = "";
    private String d7 = "";
    private String d8 = "";
    private String d9 = "";
    private String d10 = "";
    private String d11 = "";
    private String d12 = "";
    private String d13 = "";
    private String d14 = "";
    private String a1 = "";
    private String a2 = "";
    private String a3 = "";
    private String a4 = "";
    private String a5 = "";
    private String a6 = "";
    private String a7 = "";
    private String a8 = "";
    private String rx = "";
    private String tx = "";
    private Scanner pinSetter;

    public PinoutTracker(){
        pinSetter = new Scanner(System.in);
    }

    public void layoutSetter(){
        System.out.println("Assign a module pin to Digital pin D1");
        d1 = pinSetter.nextLine();
        System.out.println("Pin D1 to:" + d1);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D2");
        d2 = pinSetter.nextLine();
        System.out.println("Pin D2 to:" + d2);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D3");
        d3 = pinSetter.nextLine();
        System.out.println("Pin D3 to:" + d3);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D4");
        d4 = pinSetter.nextLine();
        System.out.println("Pin D4 to:" + d4);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D5");
        d5 = pinSetter.nextLine();
        System.out.println("Pin D5 to:" + d5);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D6");
        d6 = pinSetter.nextLine();
        System.out.println("Pin D6 to:" + d6);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D7");
        d7 = pinSetter.nextLine();
        System.out.println("Pin D7 to:" + d7);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D8");
        d8 = pinSetter.nextLine();
        System.out.println("Pin D8 to:" + d8);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D9");
        d9 = pinSetter.nextLine();
        System.out.println("Pin D9 to:" + d9);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D10");
        d10 = pinSetter.nextLine();
        System.out.println("Pin D10 to:" + d10);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D11");
        d11 = pinSetter.nextLine();
        System.out.println("Pin D11 to:" + d11);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D12");
        d12 = pinSetter.nextLine();
        System.out.println("Pin D12 to:" + d12);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D13");
        d13 = pinSetter.nextLine();
        System.out.println("Pin D13 to:" + d13);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Digital pin D14");
        d14 = pinSetter.nextLine();
        System.out.println("Pin D14 to:" + d14);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Analog pin A1");
        a1 = pinSetter.nextLine();
        System.out.println("Pin A1 to:" + a1);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Analog pin A2");
        a2 = pinSetter.nextLine();
        System.out.println("Pin A2 to:" + a2);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Analog pin A3");
        a3 = pinSetter.nextLine();
        System.out.println("Pin A3 to:" + a3);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Analog pin A4");
        a4 = pinSetter.nextLine();
        System.out.println("Pin A4 to:" + a4);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Analog pin A5");
        a5 = pinSetter.nextLine();
        System.out.println("Pin A5 to:" + a5);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Analog pin A6");
        a6 = pinSetter.nextLine();
        System.out.println("Pin A6 to:" + a6);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Analog pin A7");
        a7 = pinSetter.nextLine();
        System.out.println("Pin A7 to:" + a7);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Analog pin A8");
        a8 = pinSetter.nextLine();
        System.out.println("Pin A8 to:" + a8);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Serial pin RX");
        rx = pinSetter.nextLine();
        System.out.println("Pin RX to:" + rx);
        System.out.println("-----------------------------------------------");
        System.out.println("Assign a module pin to Serial pin TX");
        tx = pinSetter.nextLine();
        System.out.println("Pin TX to:" + tx);
        System.out.println("-----------------------------------------------");
    }
    public void layoutGetter(){
        System.out.println(d13 + " ->D13 {{{}}}{{{}}} D12<- " + d12);
        System.out.println(d13 + " ->D13 {{{}}}{{{}}} D12<- " + d12);

    }
}

